---
sidebar: sidebar 
permalink: task_completing_signing_up_marketplace.html 
keywords: netapp, saas backup, microsoft 365, getting started, sign up, signing up, paid, subscription, licensed, version 
summary: Sie können sich bei SaaS Backup für Microsoft 365 mit Ihrem Microsoft 365-Servicekonto oder mit Ihrem NetApp SSO-Konto anmelden. 
---
= Melden Sie sich mit einem kostenpflichtigen Abonnement über einen Marktplatz an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie Ihre Lizenz über einen Marketplace erworben haben, werden Ihre Lizenzinformationen angezeigt. Führen Sie die folgenden Schritte aus, um die Anmeldung abzuschließen.

.Schritte
. Klicken Sie Auf *Weiter*.
. Wählen Sie Ihr *Amazon S3* oder *Azure Blob* als Storage-Typ aus.
. Wählen Sie den Speicherbereich für Ihr Backup aus. Wählen Sie die Region aus, die dem physischen Standort der zu sichern Daten am nächsten ist. Die *bevorzugte* Region ist als solche gekennzeichnet.
. Klicken Sie Auf *Weiter*.
. Überprüfen Sie Ihre Konfiguration, und klicken Sie dann auf *Speichern*.
. Falls noch nicht geschehen, link:task_activate_support.html["Aktivieren Sie den Support"].

