---
sidebar: sidebar 
permalink: task_adding_permissions_to_service_accounts.html 
keywords: netapp, saas backup, microsoft 365, add, adding, permissions, service, accounts 
summary: Bei Bedarf können Sie weitere Konten hinzufügen, um die Backup-Performance zu verbessern. Mit Servicekonten können gleichzeitige Backups effizient durchgeführt werden. 
---
= Zusätzliche Servicekonten hinzufügen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei Bedarf können Sie zusätzliche Service-Konten hinzufügen, um die Backup-Performance zu verbessern. Mit Servicekonten können gleichzeitige Backups effizient durchgeführt werden.

.Schritte
. Melden Sie sich beim Microsoft 365 Management Portal mit einem Konto mit Administratorrechten an.
. Klicken Sie auf das Startsymbol der App und dann auf *Admin*.
. Klicken Sie auf der linken Seite auf *Benutzer* und dann auf *Aktive Benutzer*.
. Klicken Sie auf *Benutzer hinzufügen*, um ein neues Konto zu erstellen.
. Füllen Sie das Formular gemäß den Anweisungen unten aus.
+
** Verwenden Sie *Lassen Sie mich das Passwort erstellen*.
** Deaktivieren Sie *Ändern Sie das Passwort für diesen Benutzer, wenn er sich zum ersten Mal anmelden*.
** Wählen Sie die Rolle *Customized Administrator* aus.
** Wählen Sie *Exchange Administrator* und *SharePoint Administrator* aus.
** Wählen Sie *Benutzer ohne Produktlizenz erstellen*.


. Wenn Exchange-Backups mit neu erstellten Servicekonten ausgeführt werden sollen, weisen Sie diesen neu erstellten Servicekonten die Exchange-Berechtigungen zu.link:task_configuring_impersonation.html["Konfigurieren von Impersonationen"]



NOTE: SaaS Backup weist auf OneDrive und SharePoint Sites automatisch die Berechtigungen zu, müssen sie also nicht zugewiesen werden.


NOTE: Sie können Multi-Faktor-Autorisierung (MFA) für dieses Konto aktivieren.
